apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netflix-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"  # Ensures NGINX handles this Ingress
spec:
  ingressClassName: nginx
  rules:
  - host: example1.local
    http:
      paths: 
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 5173  # remove the dot
